<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>week-16-demo – CMSC 1217 : Introduction to Data Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b337f537912f5ab074b938eebad4c5d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-feb0c0ed7aac57d66ec8dce0f6a48183.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-b337f537912f5ab074b938eebad4c5d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">CMSC 1217 : Introduction to Data Analytics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Week 16 Demo: Data Aggregation and Group Operations</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
        <div class="sidebar-tools-collapse">
    <a href="https://discord.gg/az8cmeqJdc" title="" class="quarto-navigation-tool px-1" aria-label="Discord"><i class="bi bi-chat-dots"></i></a>
    <a href="https://sctcc.learn.minnstate.edu/d2l/login" title="" class="quarto-navigation-tool px-1" aria-label="D2L"><i class="bi bi-book-half"></i></a>
</div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course/syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course/schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/office-hours.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Office Hours</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/homework-coursework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment Policies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/general-policies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Policies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/ai-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI Policy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Weekly Overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-06/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6 (Starts 16 FEB)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-07/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7 (Starts 23 FEB)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-08/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 8 (Starts 2 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-10/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10 (Starts 16 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-11/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11 (Starts 23 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-12/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 12 (Starts 30 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-13/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 13 (Starts 6 APR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-14/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 14 (Starts 13 APR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-15/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 15 (Starts 20 APR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-16/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 16 (Starts 27 APR)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Weekly Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-06/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6 (Starts 16 FEB)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-07/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7 (Starts 23 FEB)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-08/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 8 (Starts 2 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-10/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 10 (Starts 16 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-11/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 11 (Starts 23 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-12/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 12 (Starts 30 MAR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-13/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 13 (Starts 6 APR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-14/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 14 (Starts 13 APR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-15/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 15 (Starts 20 APR)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-16/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 16 (Starts 27 APR)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Guides</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/setup/miniconda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Miniconda Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/setup/jupyter-learning-links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Jupyter Learning Links</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/cmsc-1217/week-02/cmsc-1217-chap-03-learning-resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 3 Reference Videos</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/cmsc-1217/week-03/cmsc-1217-chap-04-learning-resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 4 Reference Videos</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 16 Demo: Data Aggregation and Group Operations</h1>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 21, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="how-to-work-through-this-demo" class="level2">
<h2 class="anchored" data-anchor-id="how-to-work-through-this-demo">How to Work Through This Demo</h2>
<p>Before every code block, read the setup text that explains what the code is about to do. After running the cell, read the explanation that follows to understand what the output shows. Run cells in order from top to bottom. Earlier cells create variables that later cells depend on.</p>
<p>If any cell produces an error, check that you ran all the cells above it first. Use Restart Kernel and Run All to reset if needed.</p>
<hr>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Every analysis in this course so far has worked on DataFrames one row at a time. You filtered rows with boolean indexing, computed statistics on whole columns, and built visualizations from the result. What you have not yet done is compute statistics <em>within groups</em>. If you wanted the average power usage per module, or the total hours each crew member logged, the DataFrame operations you know would either require writing a loop or filtering the table once per group and combining the results by hand.</p>
<p>Chapter 10 introduces the pandas tool designed for exactly that problem: <code>groupby()</code>. The pattern is called <em>split-apply-combine</em>. You split the DataFrame into groups based on a key, apply a function to each group, and combine the results into a single output. A single line of code replaces what would otherwise be a loop that has to track which rows belong to which group.</p>
<p>If you have taken database modeling, <code>groupby()</code> will look familiar. It implements the same logic as SQL’s <code>GROUP BY</code> clause: grouping rows by a shared key and computing aggregate functions per group.</p>
<p>This demo uses an activity log from <strong>Artemis Base Gamma</strong>, a lunar research outpost with a ten-person crew operating over a twenty-sol mission window. Each row in the log is one recorded task: who did it, in which module, what kind of activity, how long it took, and how much power and oxygen it consumed. Mission Control needs summary reports of crew performance, module usage, and resource consumption. Every one of those reports is a group operation.</p>
<p>The demo follows this structure:</p>
<ol type="1">
<li>How to think about group operations</li>
<li>Aggregation with multiple keys and multiple functions</li>
<li>Apply for custom per-group operations</li>
<li>Transform for broadcasting group statistics</li>
<li>Pivot tables and cross-tabulation</li>
</ol>
<hr>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>Download <code>artemis_base_log.csv</code> from the course page and place it in your <code>week16</code> folder alongside this notebook.</p>
<div id="5d054975" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
<section id="part-1-how-to-think-about-group-operations" class="level2">
<h2 class="anchored" data-anchor-id="part-1-how-to-think-about-group-operations">Part 1: How to Think About Group Operations</h2>
<section id="load-the-activity-log" class="level3">
<h3 class="anchored" data-anchor-id="load-the-activity-log">Load the activity log</h3>
<div id="b0055ad0" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>log <span class="op">=</span> pd.read_csv(<span class="st">"artemis_base_log.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shape: </span><span class="sc">{</span>log<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.dtypes)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape: (243, 9)
sol                 int64
crew_member        object
rank               object
crew_role          object
module             object
activity_type      object
duration_hours    float64
power_kwh         float64
oxygen_liters     float64
dtype: object

   sol crew_member  rank  crew_role      module activity_type  duration_hours  \
0    1    Nakamura  Cmdr  Commander     Airlock           EVA             4.1   
1    1     Okonkwo    Lt   Engineer     Airlock   Maintenance             1.1   
2    1     Okonkwo    Lt   Engineer     Habitat   Maintenance             3.1   
3    1       Patel    Lt  Scientist         Lab      Research             5.0   
4    1     Vasquez    Lt      Medic  Greenhouse      Research             2.4   

   power_kwh  oxygen_liters  
0       5.48          169.8  
1       1.93           26.0  
2       6.57           76.3  
3      20.20           88.6  
4      10.41           42.0  </code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>The log has 243 rows and 9 columns. Each row is one logged activity. The categorical columns (<code>crew_member</code>, <code>rank</code>, <code>crew_role</code>, <code>module</code>, <code>activity_type</code>) identify who did what and where. The numeric columns (<code>duration_hours</code>, <code>power_kwh</code>, <code>oxygen_liters</code>) are the measurements.</p>
<p>Notice that <code>oxygen_liters</code> is <code>float64</code> rather than <code>int64</code> or some other integer type. That is because three rows have blank values (sensor dropouts during the mission). How <code>groupby</code> handles those missing values is covered later in Part 1.</p>
</section>
<section id="create-a-groupby-object" class="level3">
<h3 class="anchored" data-anchor-id="create-a-groupby-object">Create a GroupBy object</h3>
<p>The first step in any group operation is to call <code>.groupby()</code> on the DataFrame, passing the column you want to group by.</p>
<div id="2296082c" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>grouped <span class="op">=</span> log.groupby(<span class="st">"crew_role"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grouped)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(grouped))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;pandas.core.groupby.generic.DataFrameGroupBy object at 0x109533b60&gt;
&lt;class 'pandas.core.groupby.generic.DataFrameGroupBy'&gt;</code></pre>
</div>
</div>
<p><strong>Understanding the GroupBy object:</strong></p>
<p>The result is not a DataFrame. It is a <code>DataFrameGroupBy</code> object. Internally, pandas has identified the groups and recorded which rows belong to which group, but it has not actually computed anything yet. No aggregation runs until you ask for one by calling a method like <code>.sum()</code> or <code>.mean()</code> on the object.</p>
<p>This is the <em>split</em> step of split-apply-combine. The rows have been organized into groups (one per unique <code>crew_role</code> value), but no function has been applied yet.</p>
</section>
<section id="see-what-is-inside-the-groups" class="level3">
<h3 class="anchored" data-anchor-id="see-what-is-inside-the-groups">See what is inside the groups</h3>
<p>The GroupBy object does not display its contents when you print it, but you can iterate over it to see each group directly. Iterating yields pairs of <code>(group_name, group_rows)</code>.</p>
<div id="11e8c97e" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, group <span class="kw">in</span> log.groupby(<span class="st">"crew_role"</span>):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"--- </span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span><span class="bu">len</span>(group)<span class="sc">}</span><span class="ss"> rows) ---"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(group.head(<span class="dv">2</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>--- Commander (26 rows) ---
    sol crew_member  rank  crew_role   module  activity_type  duration_hours  \
0     1    Nakamura  Cmdr  Commander  Airlock            EVA             4.1   
12    2    Nakamura  Cmdr  Commander  Habitat  Communication             1.2   

    power_kwh  oxygen_liters  
0        5.48          169.8  
12       0.93           20.8  

--- Engineer (69 rows) ---
   sol crew_member rank crew_role   module activity_type  duration_hours  \
1    1     Okonkwo   Lt  Engineer  Airlock   Maintenance             1.1   
2    1     Okonkwo   Lt  Engineer  Habitat   Maintenance             3.1   

   power_kwh  oxygen_liters  
1       1.93           26.0  
2       6.57           76.3  

--- Medic (25 rows) ---
    sol crew_member rank crew_role      module activity_type  duration_hours  \
4     1     Vasquez   Lt     Medic  Greenhouse      Research             2.4   
22    3     Vasquez   Lt     Medic     Habitat   LifeSupport             0.7   

    power_kwh  oxygen_liters  
4       10.41           42.0  
22       0.69           15.6  

--- Scientist (49 rows) ---
   sol crew_member rank  crew_role module activity_type  duration_hours  \
3    1       Patel   Lt  Scientist    Lab      Research             5.0   
7    1       Abara  Sgt  Scientist    Lab      Research             5.4   

   power_kwh  oxygen_liters  
3      20.20           88.6  
7      26.97           94.9  

--- Specialist (74 rows) ---
   sol crew_member rank   crew_role      module  activity_type  \
6    1   Lindqvist  Sgt  Specialist  Greenhouse       Research   
8    1       Reyes  Cpl  Specialist     Habitat  Communication   

   duration_hours  power_kwh  oxygen_liters  
6             4.3      20.54           70.4  
8             0.9       0.66           13.7  
</code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>Each iteration produces one group: the group name (the unique <code>crew_role</code> value) and a smaller DataFrame containing only the rows that belong to that group. The loop runs five times because there are five unique roles. Printing the first two rows of each group confirms that the split step has already happened internally.</p>
<p>You will rarely write this loop in practice because the aggregation methods handle the splitting, applying, and combining automatically. But seeing the groups directly makes the abstraction concrete: the GroupBy object is holding a collection of smaller DataFrames, one per unique key value, ready for a function to be applied.</p>
</section>
<section id="count-rows-per-group-with-.size" class="level3">
<h3 class="anchored" data-anchor-id="count-rows-per-group-with-.size">Count rows per group with <code>.size()</code></h3>
<p>To count the rows in each group, call <code>.size()</code> on the GroupBy object.</p>
<div id="86dd30da" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.groupby(<span class="st">"crew_role"</span>).size())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>crew_role
Commander     26
Engineer      69
Medic         25
Scientist     49
Specialist    74
dtype: int64</code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>The result is a Series. The index is the unique <code>crew_role</code> values and the values are the counts. This tells you how many rows in the log belong to each role: 26 activities logged by the Commander, 69 by Engineers, 25 by the Medic, and so on.</p>
<p><code>.size()</code> counts every row in the group regardless of what is in the columns. A related method, <code>.count()</code>, counts non-null values per column and returns a DataFrame with one count per (group, column) pair. For a simple row count, use <code>.size()</code>.</p>
</section>
<section id="compute-a-group-mean" class="level3">
<h3 class="anchored" data-anchor-id="compute-a-group-mean">Compute a group mean</h3>
<p>To compute an aggregated statistic instead of a row count, select the column you want to aggregate and call an aggregation method on it.</p>
<div id="1e56e7b8" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.groupby(<span class="st">"module"</span>)[<span class="st">"power_kwh"</span>].mean().<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>module
Airlock          6.81
Greenhouse       9.45
Habitat          1.74
Lab             12.83
PowerStation     5.50
Name: power_kwh, dtype: float64</code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>This is the split-apply-combine pattern in full:</p>
<ul>
<li><strong>Split:</strong> the log is grouped by <code>module</code>.</li>
<li><strong>Apply:</strong> <code>.mean()</code> is computed on the <code>power_kwh</code> column of each group.</li>
<li><strong>Combine:</strong> the five group means are assembled into a Series indexed by module name.</li>
</ul>
<p>Lab activities average 12.83 kWh per task, Greenhouse activities average 9.45 kWh, and Habitat activities average 1.74 kWh. The Lab uses roughly seven times the power per task that the Habitat does, which matches expectations because Lab instruments are energy-intensive while Habitat activities are mostly communication and light life support.</p>
</section>
<section id="missing-values-are-dropped-automatically" class="level3">
<h3 class="anchored" data-anchor-id="missing-values-are-dropped-automatically">Missing values are dropped automatically</h3>
<p>The <code>oxygen_liters</code> column has three missing values. Aggregating it demonstrates how <code>groupby</code> treats those missing entries.</p>
<div id="4e4715a4" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.groupby(<span class="st">"crew_role"</span>)[<span class="st">"oxygen_liters"</span>].mean().<span class="bu">round</span>(<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>crew_role
Commander      60.9
Engineer       91.2
Medic          50.8
Scientist      65.2
Specialist    109.3
Name: oxygen_liters, dtype: float64</code></pre>
</div>
</div>
<p><strong>Understanding the default behavior:</strong></p>
<p>The result is a clean Series with no warnings and no <code>NaN</code> values anywhere. By default, <code>groupby</code> excludes missing values from aggregation calculations. The three rows with missing oxygen measurements are simply left out of the mean for whichever group they belong to.</p>
<p>This is usually the behavior you want. If a sensor failed on three EVAs, you do not want those gaps to distort the mean for the whole group.</p>
</section>
<section id="include-missing-values-as-their-own-group" class="level3">
<h3 class="anchored" data-anchor-id="include-missing-values-as-their-own-group">Include missing values as their own group</h3>
<p>Missing values in the <em>grouping key</em> are a different situation. By default, rows with a missing group key are excluded entirely from the result. To include them as their own <code>NaN</code> group, pass <code>dropna=False</code> to <code>groupby</code>.</p>
<div id="d9e370f1" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set one crew_role value to NaN to show how dropna works</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>log_with_missing <span class="op">=</span> log.copy()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>log_with_missing.loc[<span class="dv">0</span>, <span class="st">"crew_role"</span>] <span class="op">=</span> np.nan</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Default behavior: missing keys are dropped</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Default (dropna=True):"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log_with_missing.groupby(<span class="st">"crew_role"</span>).size())</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># With dropna=False: missing keys become a NaN group</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"With dropna=False:"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log_with_missing.groupby(<span class="st">"crew_role"</span>, dropna<span class="op">=</span><span class="va">False</span>).size())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Default (dropna=True):
crew_role
Commander     25
Engineer      69
Medic         25
Scientist     49
Specialist    74
dtype: int64

With dropna=False:
crew_role
Commander     25
Engineer      69
Medic         25
Scientist     49
Specialist    74
NaN            1
dtype: int64</code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>With the default behavior, the row with a missing <code>crew_role</code> is silently excluded. The group counts sum to 242 instead of 243. With <code>dropna=False</code>, a <code>NaN</code> group appears in the result containing the one missing-key row. The total now matches.</p>
<p>Which behavior is correct depends on the analysis. If missing group keys represent incomplete records that should not contribute to the summary, the default is fine. If missing group keys are themselves meaningful (an “uncategorized” category worth reporting), use <code>dropna=False</code>.</p>
<hr>
</section>
</section>
<section id="part-2-aggregation-with-multiple-keys-and-multiple-functions" class="level2">
<h2 class="anchored" data-anchor-id="part-2-aggregation-with-multiple-keys-and-multiple-functions">Part 2: Aggregation with Multiple Keys and Multiple Functions</h2>
<section id="group-by-multiple-keys" class="level3">
<h3 class="anchored" data-anchor-id="group-by-multiple-keys">Group by multiple keys</h3>
<p>Passing a list of columns to <code>groupby</code> creates groups defined by unique combinations of those columns.</p>
<div id="514b77fd" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.groupby([<span class="st">"crew_role"</span>, <span class="st">"activity_type"</span>])[<span class="st">"duration_hours"</span>].<span class="bu">sum</span>().<span class="bu">round</span>(<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>crew_role   activity_type
Commander   Communication     15.8
            EVA               23.4
            LifeSupport        2.4
            Maintenance        2.2
            Research          10.2
Engineer    Communication      5.2
            EVA               68.2
            LifeSupport       15.6
            Maintenance       99.2
            Research          18.2
Medic       Communication      1.2
            EVA                8.2
            LifeSupport       20.2
            Maintenance        5.4
            Research          14.9
Scientist   Communication      4.4
            EVA               11.9
            LifeSupport        7.2
            Maintenance       15.5
            Research         108.2
Specialist  Communication     15.6
            EVA              132.3
            LifeSupport       10.3
            Maintenance       26.2
            Research          59.6
Name: duration_hours, dtype: float64</code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>The result is a Series with a hierarchical index (a <code>MultiIndex</code> from Week 12’s chapter). The outer level is <code>crew_role</code> and the inner level is <code>activity_type</code>. Each unique combination of the two is one group, and the value is the total hours logged for that combination.</p>
<p>You can read the result as: Commanders logged 23.4 total hours of EVA activity; Engineers logged 99.2 total hours of Maintenance; Scientists logged 108.2 total hours of Research. The role specialization pattern is visible in the numbers.</p>
<p>The hierarchical index is the natural output shape for multi-key groupings. If you want it as a two-dimensional table with <code>crew_role</code> as rows and <code>activity_type</code> as columns, <code>.unstack()</code> from Chapter 8 does exactly that.</p>
</section>
<section id="aggregate-with-.agg-using-a-single-function" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-with-.agg-using-a-single-function">Aggregate with <code>.agg()</code> using a single function</h3>
<p>The <code>.agg()</code> method is the general-purpose aggregation interface. Called with a single string, it does the same thing as the matching method call.</p>
<div id="c72ca94c" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.groupby(<span class="st">"module"</span>)[<span class="st">"power_kwh"</span>].agg(<span class="st">"mean"</span>).<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>module
Airlock          6.81
Greenhouse       9.45
Habitat          1.74
Lab             12.83
PowerStation     5.50
Name: power_kwh, dtype: float64</code></pre>
</div>
</div>
<p><strong>Understanding <code>.agg()</code>:</strong></p>
<p>This produces the same result as <code>log.groupby("module")["power_kwh"].mean()</code>. For simple cases, the method call is shorter and preferred. <code>.agg()</code> becomes useful when you want to apply multiple functions at once or different functions to different columns.</p>
</section>
<section id="apply-multiple-aggregation-functions-at-once" class="level3">
<h3 class="anchored" data-anchor-id="apply-multiple-aggregation-functions-at-once">Apply multiple aggregation functions at once</h3>
<p>Passing a list to <code>.agg()</code> computes all the listed functions and returns a DataFrame with one column per function.</p>
<div id="5f5fef8d" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log.groupby(<span class="st">"module"</span>)[<span class="st">"power_kwh"</span>].agg([<span class="st">"count"</span>, <span class="st">"mean"</span>, <span class="st">"sum"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>]).<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              count   mean     sum   min    max
module                                         
Airlock          62   6.81  422.02  1.93  12.11
Greenhouse       48   9.45  453.64  0.55  29.97
Habitat          71   1.74  123.22  0.38   7.43
Lab              50  12.83  641.31  1.86  27.05
PowerStation     12   5.50   65.94  2.96   7.96</code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>The result is a DataFrame indexed by module, with one column per aggregation. From the Lab row alone you can read that 50 activities were logged in the Lab, averaging 12.83 kWh each, summing to 641.31 kWh total, with individual tasks ranging from 1.86 kWh to 27.05 kWh.</p>
<p>The function names become the column names automatically. String names are available for the common built-in aggregations: <code>count</code>, <code>mean</code>, <code>sum</code>, <code>min</code>, <code>max</code>, <code>median</code>, <code>std</code>, <code>var</code>, <code>first</code>, <code>last</code>. These built-in versions are written in optimized low-level code, which makes them faster than a custom Python function passed to <code>.agg()</code>. For everyday aggregations, prefer the string names.</p>
</section>
<section id="apply-different-functions-to-different-columns" class="level3">
<h3 class="anchored" data-anchor-id="apply-different-functions-to-different-columns">Apply different functions to different columns</h3>
<p>Passing a dictionary to <code>.agg()</code> applies a different aggregation to each named column.</p>
<div id="d0dbd20b" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mission_summary <span class="op">=</span> log.groupby(<span class="st">"crew_role"</span>).agg({</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"duration_hours"</span>: <span class="st">"sum"</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"power_kwh"</span>: <span class="st">"mean"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"oxygen_liters"</span>: <span class="st">"sum"</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mission_summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            duration_hours  power_kwh  oxygen_liters
crew_role                                           
Commander             54.0       3.71         1584.5
Engineer             206.4       5.77         6200.4
Medic                 49.9       4.68         1271.2
Scientist            147.2      11.19         3129.9
Specialist           244.0       7.39         7981.3</code></pre>
</div>
</div>
<p><strong>Understanding the dictionary form:</strong></p>
<p>The keys of the dictionary are column names in the source DataFrame. The values are the aggregation functions to apply to each. For the Artemis log, this produces a clean mission summary: total hours worked per role, average power per task per role, and total oxygen consumed per role.</p>
<p>The total hours column reveals how work was distributed: Engineers logged 206.4 hours and Specialists logged 244.0 hours, while the Commander logged only 54.0.</p>
</section>
<section id="return-aggregated-results-without-a-group-key-index" class="level3">
<h3 class="anchored" data-anchor-id="return-aggregated-results-without-a-group-key-index">Return aggregated results without a group-key index</h3>
<p>By default, the group keys become the index of the result. To return them as regular columns instead, pass <code>as_index=False</code> to <code>groupby</code>.</p>
<div id="38ca4be1" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>flat_summary <span class="op">=</span> log.groupby(<span class="st">"crew_role"</span>, as_index<span class="op">=</span><span class="va">False</span>).agg({</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"duration_hours"</span>: <span class="st">"sum"</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"power_kwh"</span>: <span class="st">"mean"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"oxygen_liters"</span>: <span class="st">"sum"</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(flat_summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    crew_role  duration_hours  power_kwh  oxygen_liters
0   Commander            54.0       3.71         1584.5
1    Engineer           206.4       5.77         6200.4
2       Medic            49.9       4.68         1271.2
3   Scientist           147.2      11.19         3129.9
4  Specialist           244.0       7.39         7981.3</code></pre>
</div>
</div>
<p><strong>Understanding <code>as_index=False</code>:</strong></p>
<p>The result has <code>crew_role</code> as a regular column rather than as the index. This is often what you want when the next step is to save the summary to a CSV file, merge it with another DataFrame, or pass it to a plotting function that expects a flat DataFrame.</p>
<p>The same result can be produced by calling <code>.reset_index()</code> on the indexed version, but <code>as_index=False</code> is faster because it avoids building the index in the first place.</p>
<hr>
</section>
</section>
<section id="part-3-apply-for-custom-per-group-operations" class="level2">
<h2 class="anchored" data-anchor-id="part-3-apply-for-custom-per-group-operations">Part 3: Apply for Custom Per-Group Operations</h2>
<p><code>.agg()</code> works when you want a single value per group (a scalar like a sum or a mean). When you want something more complex from each group, such as the top N rows by some criterion or a custom calculation that returns multiple rows, use <code>.apply()</code>.</p>
<section id="return-the-top-activities-per-crew-member" class="level3">
<h3 class="anchored" data-anchor-id="return-the-top-activities-per-crew-member">Return the top activities per crew member</h3>
<p>Suppose Mission Control wants to see each crew member’s two longest-duration activities. The question requires returning multiple rows per group, which rules out <code>.agg()</code>. Define a function that takes a DataFrame and returns the top N rows by duration, then apply it per group.</p>
<div id="2c772d19" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> top_n(group, n<span class="op">=</span><span class="dv">2</span>):</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> group.sort_values(<span class="st">"duration_hours"</span>, ascending<span class="op">=</span><span class="va">False</span>).head(n)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>top_activities <span class="op">=</span> log.groupby(<span class="st">"crew_member"</span>)[</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"activity_type"</span>, <span class="st">"module"</span>, <span class="st">"duration_hours"</span>]</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>].<span class="bu">apply</span>(top_n, n<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(top_activities)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                activity_type      module  duration_hours
crew_member                                              
Abara       39       Research  Greenhouse             5.7
            153      Research         Lab             5.6
Chen        24       Research  Greenhouse             6.0
            197           EVA     Airlock             5.4
Lindqvist   151           EVA     Airlock             6.8
            74            EVA     Airlock             6.8
Muller      157           EVA     Airlock             6.5
            30            EVA     Airlock             6.3
Nakamura    231           EVA     Airlock             6.9
            67            EVA     Airlock             6.0
Okonkwo     160           EVA     Airlock             7.4
            93            EVA     Airlock             5.9
Patel       186      Research  Greenhouse             5.2
            3        Research         Lab             5.0
Reyes       51            EVA     Airlock             7.4
            192           EVA     Airlock             6.2
Torres      52            EVA     Airlock             7.0
            88            EVA     Airlock             6.5
Vasquez     23       Research  Greenhouse             5.9
            121           EVA     Airlock             5.1</code></pre>
</div>
</div>
<p><strong>Understanding <code>.apply()</code>:</strong></p>
<p><code>.apply()</code> splits the DataFrame into groups, calls the function on each group, and combines the results. The function receives a smaller DataFrame containing only the rows for one group, and it can return whatever makes sense for the analysis: a single value, a Series, or a DataFrame. Here it returns a DataFrame of two rows per group, and <code>.apply()</code> stacks them into one combined result.</p>
<p>Selecting the three columns before calling <code>.apply()</code> (<code>[["activity_type", "module", "duration_hours"]]</code>) keeps the output focused on what matters. Without that selection, every column of the log would appear in the result, which would be harder to read.</p>
<p><code>.apply()</code> is the most general GroupBy method, but that flexibility has a cost: it is slower than the built-in aggregations like <code>.sum()</code> and <code>.mean()</code> because it calls your Python function once per group. For simple aggregations, prefer <code>.agg()</code> with the built-in function names.</p>
<hr>
</section>
</section>
<section id="part-4-transform-for-broadcasting-group-statistics" class="level2">
<h2 class="anchored" data-anchor-id="part-4-transform-for-broadcasting-group-statistics">Part 4: Transform for Broadcasting Group Statistics</h2>
<p><code>.agg()</code> and <code>.apply()</code> both <em>shrink</em> the data. The output has one row per group, which is fewer rows than the original DataFrame. For the Artemis log, <code>.agg("sum")</code> on <code>duration_hours</code> grouped by <code>crew_member</code> would produce a 10-row Series: one total per crew member.</p>
<p>Sometimes you want the opposite. You want to compute a group statistic and then attach it back to every row in the original DataFrame, so you can use it in a per-row calculation. You still need the per-group total, but you also need it available on every original row, not collapsed into a 10-row summary.</p>
<p><code>.transform()</code> does exactly that. It computes a value for each group, then copies that value back onto every row that belongs to the group. The result has 243 rows, the same as the original log. Pandas calls this “broadcasting” a value: the single group value gets spread out across all the rows in the group.</p>
<section id="compute-each-activity-as-a-percentage-of-the-crew-members-total" class="level3">
<h3 class="anchored" data-anchor-id="compute-each-activity-as-a-percentage-of-the-crew-members-total">Compute each activity as a percentage of the crew member’s total</h3>
<p>To flag which activities represented a large share of a crew member’s time, you need each row’s duration as a percentage of that crew member’s total duration. That requires two pieces of information on each row: the row’s own duration (already there) and the crew member’s total (needs to be computed per group and attached).</p>
<div id="802379d9" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>log[<span class="st">"crew_total_hours"</span>] <span class="op">=</span> log.groupby(<span class="st">"crew_member"</span>)[<span class="st">"duration_hours"</span>].transform(<span class="st">"sum"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>log[<span class="st">"pct_of_crew_hours"</span>] <span class="op">=</span> (log[<span class="st">"duration_hours"</span>] <span class="op">/</span> log[<span class="st">"crew_total_hours"</span>] <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log[[<span class="st">"crew_member"</span>, <span class="st">"duration_hours"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>           <span class="st">"crew_total_hours"</span>, <span class="st">"pct_of_crew_hours"</span>]].head(<span class="dv">10</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  crew_member  duration_hours  crew_total_hours  pct_of_crew_hours
0    Nakamura             4.1              54.0                7.6
1     Okonkwo             1.1              66.5                1.7
2     Okonkwo             3.1              66.5                4.7
3       Patel             5.0              76.4                6.5
4     Vasquez             2.4              49.9                4.8
5        Chen             3.2              67.5                4.7
6   Lindqvist             4.3              91.7                4.7
7       Abara             5.4              70.8                7.6
8       Reyes             0.9              76.3                1.2
9      Torres             2.6              72.4                3.6</code></pre>
</div>
</div>
<p><strong>Understanding <code>.transform()</code>:</strong></p>
<p><code>.transform("sum")</code> computes the sum of <code>duration_hours</code> within each <code>crew_member</code> group, then copies that single per-group value back to every row belonging to the group. The result has 243 rows (the same number as the original log), not one row per crew member.</p>
<p>Compare this to <code>.agg("sum")</code>, which would have produced a 10-row Series (one sum per crew member). Because <code>.transform()</code> produces one value per original row rather than one per group, the result can be assigned directly as a new column on the original DataFrame.</p>
<p>Once the group total is on every row, computing the per-row percentage is a standard column-arithmetic operation. The first entry in the output shows Nakamura’s 4.1-hour activity representing 7.6% of their 54.0 total mission hours.</p>
<p><code>.transform()</code> is the pattern for normalizing values within groups, computing running totals within groups, or comparing individual rows to their group’s average.</p>
<hr>
</section>
</section>
<section id="part-5-pivot-tables-and-cross-tabulation" class="level2">
<h2 class="anchored" data-anchor-id="part-5-pivot-tables-and-cross-tabulation">Part 5: Pivot Tables and Cross-Tabulation</h2>
<section id="the-pivot_table-method" class="level3">
<h3 class="anchored" data-anchor-id="the-pivot_table-method">The <code>pivot_table</code> method</h3>
<p>A <em>pivot table</em> is a two-dimensional summary where one variable is arranged along the rows and another along the columns. Pivot tables are the standard reporting format in spreadsheet applications like Excel, and pandas provides them through the <code>pivot_table</code> method.</p>
<p>Every pivot table is internally a <code>groupby</code> followed by a reshape. The method exists because the pattern is so common that having a dedicated interface is cleaner than writing the equivalent <code>groupby().agg().unstack()</code> by hand.</p>
</section>
<section id="a-basic-pivot-table" class="level3">
<h3 class="anchored" data-anchor-id="a-basic-pivot-table">A basic pivot table</h3>
<div id="a794fb67" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>module_activity <span class="op">=</span> log.pivot_table(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span><span class="st">"module"</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span><span class="st">"activity_type"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span><span class="st">"duration_hours"</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    aggfunc<span class="op">=</span><span class="st">"sum"</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(module_activity.<span class="bu">round</span>(<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>activity_type  Communication    EVA  LifeSupport  Maintenance  Research
module                                                                 
Airlock                  NaN  244.0          NaN         31.7       NaN
Greenhouse               NaN    NaN         29.4          NaN      93.6
Habitat                 42.2    NaN         26.3         31.8       NaN
Lab                      NaN    NaN          NaN         52.1     117.5
PowerStation             NaN    NaN          NaN         32.9       NaN</code></pre>
</div>
</div>
<p><strong>Understanding <code>pivot_table</code>:</strong></p>
<p>The four main arguments:</p>
<ul>
<li><code>index</code>: the column whose unique values become the row labels</li>
<li><code>columns</code>: the column whose unique values become the column labels</li>
<li><code>values</code>: the column whose values are aggregated</li>
<li><code>aggfunc</code>: the function used to aggregate the values in each cell</li>
</ul>
<p>Modules run down the rows, activity types across the columns, and total hours logged appear in each cell. The <code>NaN</code> values mark combinations that never occurred. EVAs only happen through the Airlock; Research only happens in the Lab and Greenhouse; Communication only happens in the Habitat.</p>
</section>
<section id="replace-missing-cells-with-zero" class="level3">
<h3 class="anchored" data-anchor-id="replace-missing-cells-with-zero">Replace missing cells with zero</h3>
<p>For a reporting view, you usually want empty combinations to show as zero rather than as <code>NaN</code>. Pass <code>fill_value=0</code>.</p>
<div id="87710980" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>module_activity_filled <span class="op">=</span> log.pivot_table(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span><span class="st">"module"</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span><span class="st">"activity_type"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span><span class="st">"duration_hours"</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    aggfunc<span class="op">=</span><span class="st">"sum"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    fill_value<span class="op">=</span><span class="dv">0</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(module_activity_filled.<span class="bu">round</span>(<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>activity_type  Communication    EVA  LifeSupport  Maintenance  Research
module                                                                 
Airlock                  0.0  244.0          0.0         31.7       0.0
Greenhouse               0.0    0.0         29.4          0.0      93.6
Habitat                 42.2    0.0         26.3         31.8       0.0
Lab                      0.0    0.0          0.0         52.1     117.5
PowerStation             0.0    0.0          0.0         32.9       0.0</code></pre>
</div>
</div>
<p><strong>Understanding <code>fill_value</code>:</strong></p>
<p>The <code>NaN</code> entries are replaced with 0 in the output. A module-activity combination with no logged hours now shows as zero rather than as missing.</p>
<p>Be deliberate about when you use <code>fill_value</code>. If the distinction between “no activity was logged” and “activity was logged but its total was zero” matters for your analysis, keep the <code>NaN</code> so you can tell the two apart. For a summary report where those cases mean the same thing, <code>fill_value=0</code> produces a cleaner table.</p>
</section>
<section id="add-row-and-column-totals" class="level3">
<h3 class="anchored" data-anchor-id="add-row-and-column-totals">Add row and column totals</h3>
<p>Adding <code>margins=True</code> appends an “All” row and an “All” column containing the totals.</p>
<div id="56ddd34d" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>module_activity_totals <span class="op">=</span> log.pivot_table(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span><span class="st">"module"</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span><span class="st">"activity_type"</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span><span class="st">"duration_hours"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    aggfunc<span class="op">=</span><span class="st">"sum"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    fill_value<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    margins<span class="op">=</span><span class="va">True</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(module_activity_totals.<span class="bu">round</span>(<span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>activity_type  Communication    EVA  LifeSupport  Maintenance  Research    All
module                                                                        
Airlock                  0.0  244.0          0.0         31.7       0.0  275.7
Greenhouse               0.0    0.0         29.4          0.0      93.6  123.0
Habitat                 42.2    0.0         26.3         31.8       0.0  100.3
Lab                      0.0    0.0          0.0         52.1     117.5  169.6
PowerStation             0.0    0.0          0.0         32.9       0.0   32.9
All                     42.2  244.0         55.7        148.5     211.1  701.5</code></pre>
</div>
</div>
<p><strong>Understanding <code>margins</code>:</strong></p>
<p>The bottom row shows totals across all modules for each activity type. The rightmost column shows totals across all activity types for each module. The bottom-right corner is the grand total: the sum of all duration_hours in the entire log.</p>
<p>Marginal totals are standard in reporting because they let a reader check individual cells against the row and column totals at a glance. The default name for the margin row and column is <code>"All"</code>; pass <code>margins_name="Total"</code> or any other string to change it.</p>
</section>
<section id="change-the-aggregation-function" class="level3">
<h3 class="anchored" data-anchor-id="change-the-aggregation-function">Change the aggregation function</h3>
<p>The <code>aggfunc</code> argument accepts any function name that <code>groupby</code> accepts. Using <code>"mean"</code> gives you average task duration per cell instead of the total.</p>
<div id="6aaccc80" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>module_activity_mean <span class="op">=</span> log.pivot_table(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span><span class="st">"module"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span><span class="st">"activity_type"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span><span class="st">"duration_hours"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    aggfunc<span class="op">=</span><span class="st">"mean"</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    fill_value<span class="op">=</span><span class="dv">0</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(module_activity_mean.<span class="bu">round</span>(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>activity_type  Communication   EVA  LifeSupport  Maintenance  Research
module                                                                
Airlock                 0.00  4.98         0.00         2.44      0.00
Greenhouse              0.00  0.00         1.28         0.00      3.74
Habitat                 1.03  0.00         1.32         3.18      0.00
Lab                     0.00  0.00         0.00         2.60      3.92
PowerStation            0.00  0.00         0.00         2.74      0.00</code></pre>
</div>
</div>
<p><strong>Understanding the output:</strong></p>
<p>The same pivot structure now shows average duration per task. EVAs through the Airlock average about 4.98 hours per task; Research sessions in the Lab average 3.92 hours. The story is different from the total-hours view: totals tell you where time was <em>spent</em> overall, while means tell you how long individual tasks of each type typically ran.</p>
</section>
<section id="cross-tabulation-with-pd.crosstab" class="level3">
<h3 class="anchored" data-anchor-id="cross-tabulation-with-pd.crosstab">Cross-tabulation with <code>pd.crosstab</code></h3>
<p>When the aggregation you want is simply a count of rows (how many observations fall into each cell), pandas provides a specialized function, <code>pd.crosstab</code>. It is shorthand for a <code>pivot_table</code> call with <code>aggfunc="count"</code>.</p>
<div id="09490a2e" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>role_activity_freq <span class="op">=</span> pd.crosstab(log[<span class="st">"crew_role"</span>], log[<span class="st">"activity_type"</span>], margins<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(role_activity_freq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>activity_type  Communication  EVA  LifeSupport  Maintenance  Research  All
crew_role                                                                 
Commander                 16    5            2            1         2   26
Engineer                   4   13           11           36         5   69
Medic                      2    2           15            2         4   25
Scientist                  4    3            7            7        28   49
Specialist                15   26            8            9        16   74
All                       41   49           43           55        55  243</code></pre>
</div>
</div>
<p><strong>Understanding <code>pd.crosstab</code>:</strong></p>
<p>The first two arguments are the row and column variables. Unlike <code>pivot_table</code>, which takes column names and a DataFrame, <code>crosstab</code> takes the Series themselves. The result is a frequency table: the number of activities logged for each (crew_role, activity_type) combination.</p>
<p>The pattern shows the crew’s work distribution clearly. Engineers logged 36 Maintenance activities, Scientists logged 28 Research activities, and Specialists spread their work across categories with a heavy concentration in EVA (26) and Communication (15). The “All” row and column are the marginal totals, the same as they would be in a <code>pivot_table</code> call with <code>margins=True</code>.</p>
<p><code>crosstab</code> is the right tool when you want a frequency table. For anything more complex (sums, means, custom functions), use <code>pivot_table</code>.</p>
<hr>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<section id="what-youve-learned" class="level3">
<h3 class="anchored" data-anchor-id="what-youve-learned">What You’ve Learned</h3>
<p><code>groupby()</code> creates a <code>DataFrameGroupBy</code> object that splits the DataFrame by one or more keys. No computation runs until you ask for one by calling an aggregation method. Aggregation methods like <code>.mean()</code>, <code>.sum()</code>, <code>.count()</code>, and <code>.size()</code> compute a single value per group. Missing values in the aggregated column are excluded automatically; missing values in the group key are excluded by default and included with <code>dropna=False</code>.</p>
<p><code>.agg()</code> is the general aggregation interface. Called with a string, it behaves like the matching method. Called with a list of function names, it computes every function and returns a DataFrame with one column per function. Called with a dictionary mapping column names to function names, it applies a different aggregation to each column. The dictionary form is the most common shape for building summary reports.</p>
<p><code>.apply()</code> is the most general GroupBy method. It passes each group as a smaller DataFrame to a function you write and combines the results into an output. Use it when you need multiple rows per group or custom logic that <code>.agg()</code> cannot express. <code>.transform()</code> also performs a per-group computation, but instead of returning one row per group, it copies the group value back to every original row. The result has the same number of rows as the input, so it can be assigned directly as a new column.</p>
<p><code>pivot_table</code> produces two-dimensional summaries with group keys along both axes. The <code>index</code>, <code>columns</code>, <code>values</code>, and <code>aggfunc</code> arguments map directly onto a <code>groupby</code> followed by a reshape. <code>fill_value</code> replaces missing cells with a constant; <code>margins=True</code> adds row and column totals. <code>pd.crosstab</code> is a specialized version of <code>pivot_table</code> for frequency tables.</p>
</section>
<section id="what-the-textbook-covers-next" class="level3">
<h3 class="anchored" data-anchor-id="what-the-textbook-covers-next">What the Textbook Covers Next</h3>
<p>Chapter 10 covers several topics not included in this demo.</p>
<p><strong>Custom aggregation functions.</strong> You can pass a user-defined Python function to <code>.agg()</code> and it will be applied per group. The textbook shows examples with lambda functions and named tuples for assigning column names to custom aggregations. Optimized built-in functions are faster, so reserve custom functions for cases where no built-in does the job.</p>
<p><strong>Filtering groups.</strong> <code>.filter()</code> keeps or drops whole groups based on a group-level condition. For example, keeping only groups whose size exceeds some threshold, or whose group mean is above a cutoff.</p>
<p><strong>Grouping by index level.</strong> When a DataFrame has a hierarchical index (a <code>MultiIndex</code> from Chapter 8), you can group by an index level directly using <code>level=</code> instead of a column name.</p>
<p><strong>Group transforms with unwrapped output.</strong> Beyond the <code>transform("sum")</code> pattern shown in the demo, Chapter 10 covers more sophisticated within-group operations, including ranking rows within their group, centering each value by subtracting the group’s mean, and writing custom transform functions.</p>
<p><strong>Quantile analysis.</strong> The <code>qcut</code> function and the <code>.quantile()</code> GroupBy method support grouping rows into quantile bins and analyzing each bin separately. This pattern comes up in segmentation work, where you want to compare the top 25% of observations against the bottom 25%.</p>
<p><strong>Hierarchical column output.</strong> Aggregating multiple columns with a list of functions produces a DataFrame with hierarchical column labels (a column <code>MultiIndex</code>). The textbook shows how to work with that output shape.</p>
</section>
<section id="applying-these-tools-in-week-17" class="level3">
<h3 class="anchored" data-anchor-id="applying-these-tools-in-week-17">Applying These Tools in Week 17</h3>
<p>Week 17 is a cumulative application week. You will work with a new dataset that requires you to compute grouped summaries, build a pivot table, and interpret the results in context. The Chapter 10 tools are the primary skills being applied, alongside the data preparation and visualization skills from earlier chapters.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/SCTCC-Computer-Programming\.github\.io\/cmsc-1217\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>